### ISSUE TITLE
Consider merging TargetExtractor/ResourceIdentifier and PreferenceParser/RepresentationPreferences into one RequestParser/Task object

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#15]
There are several parameters that describe a task, and in HTTP, those are usually structured as URI + verb + headers, but you probably don't want to couple to that too tightly.

Some parts of the task description are relevant for the Authorizer, others for the Operation, others potentially for the ResponseWriter. So in order to avoid a kitchen sink object, I like how CredentialsExtractor is separate. But TargetExtractor/ResourceIdentifier and PreferenceParser/RepresentationPreferences are both parsing data from the HTTP request that is destined for the Operation, so in order to reduce the number of arguments an Operation takes, and to reduce the knowledge tied into the architecture about that, I think it would be better to put them together into one 'operation task'.

To give an example, imagine that at one point an operation wants to access the remote IP address, to give geo-specific functionality. The remote IP address is neither a preference nor a ResourceIdentifier, so that would then require changing the Operation interface. If you put it into a more abstract 'Task' object, then you stay more flexible in that respect.

**Comment by RubenVerborgh** [comment]
> in order to reduce the number of arguments an Operation takes, and to reduce the knowledge tied into the architecture about that, I think it would be better to put them together into one 'operation task'.

Couple of points here:

- Reducing the number of arguments to an `Operation` is not a goal in itself (although some consequences of this might be desired).
- An `Operation` is created by an `OperationFactory`, which encapsulates the parameters that an `Operation` should receive. (Yet of course, that factory method also needs parameters; it's just that those are decoupled.)
- However, and most importantly, the separation or merging of `TargetExtractor`/`BodyParser`/`PreferenceParser` are _independent_ of the parameters an `Operation` takes. There is a difference between separating the parsers, and whether or not their data objects are separate. To be specific, `createOperation` will very likely receive a single object that combines all of these parameters (as you can for example see [here](https://github.com/RubenVerborgh/solid-server-ts/blob/a93717ec02389ba10c79975fc2bbdbe8d18336f0/src/ldp/operations/LdpOperationFactory.ts#L37)).

So we need to separate the availability of multiple parsers from the availability of multiple data objects; both issues are orthogonal.

### Choice for multiple parsers

The reason for multiple parsers is that request parsing is a complex task. One of the ideas behind OO is to manage complexity by dividing it across different components, which each can be tested independently.

For instance, is extracting the URL from an HTTP request a trivial task?
Turns out it's not: https://github.com/RubenVerborgh/solid-server-ts/blob/a93717ec02389ba10c79975fc2bbdbe8d18336f0/src/http/TargetExtractor.ts#L30-L43 And then we have not yet taken Unicode/Punycode into account, the fact that we could be tricked into dereferencing localhost, and special headers behind proxies.

Method extraction (not pictured in the diagram) must surely be a trivial task?
Turns out there's `X-Http-Method-Override` and other weird cases.

Sure, we _could_ bring them together in one parser. But then all those smaller complex pieces form one complex class. And then we lose one of our main OO tools for managing complexity.

Also, testing becomes more complex. Check out these example cases: https://github.com/RubenVerborgh/solid-server-ts/blob/a93717ec02389ba10c79975fc2bbdbe8d18336f0/test/unit/http/TargetExtractor.ts We can guarantee that they will execute fine, _independently_ of other factors. Sure, you can test the same things on a combined parser, but guaranteeing independence would mean testing all of these in all circumstances. e.g., theoretically, you would have to test that invalid hostnames are rejected for `GET`, `POST`, etc. This is a trivial example case, and of course, no one will actually do that, but the bigger argument is that we leave open many more bug vectors because we did not separate complexity.

### Choice for multiple data objects

The idea here is to give objects no more data than they need. There were many problems with that in NSS, where objects being passed in data they didn't need, started relying on that data. It's essentially the Law of Demeter again.

For example, `hasPermissions` only needs to know about credentials, `ResourceIdentifier`, `PermissionSet`. It does not need to know about methods or operations, etc. So this is why the `ResourceIdentifier` is a separate data object, because if it weren't, we would be passing in the entire `Task`. This would mean that `Authorizer` suddenly knows about `LDP` etc., while it currently only knows about IRIs. So again, minimizing knowledge. Note how the `Authorization` is completely independent of `LDP` in the architectural diagram, and can thus be tested and reused independently. Related reading: http://misko.hevery.com/2008/07/18/breaking-the-law-of-demeter-is-like-looking-for-a-needle-in-the-haystack/

-----

> To give an example, imagine that at one point an operation wants to access the remote IP address, to give geo-specific functionality. The remote IP address is neither a preference nor a ResourceIdentifier

(I would still call it a preference though, if it changes the representation based on geographic location. But that's not the core point here indeed.)

But the good thing is, from a separation of parser perspective, that then only one small component (let's say `PreferenceParser`) would need to be changed, as opposed to a much bigger and more complex parser, with consequences on testing, etc.

Changing a small component is easier and safer than changing a big one, so already this is an argument in favor of more dedicated parsers.

> so that would then require changing the Operation interface. If you put it into a more abstract 'Task' object, then you stay more flexible in that respect.

Ah, but that's a false dichotomy. You _are_ changing the `Operation` interface, because it now expects a different object, namely `Taskv2` instead of `Taskv1`. You just don't _see_ that reflected in the method signature because you are pointing to an external object.

But yes, an extra argument would need to be passed then (if deemed not a preference).

If such changes are expected frequently, then it might be a good idea to create a `RequestParser` object whose _sole_ task is to invoke _other_ parsers and combine their output into a plain JavaScript object (which would amount to `ParsedRequest` or `Task`). That `RequestParser` would  then _not_ know about the specific parsers, but rather be passed a key/value object of parsers, invoke them one by one, and place their results into an object. That way, complexity is unaffected.

Then `LdpHandler` could send that more complex object straight to the `OperationFactory`, while still cherry-picking elements out of it for the purpose of keeping `Authorizer` unaware of LDP.

However, note in general that the purpose of a sustainable architecture is not to _avoid_ change to components, but rather to keep the _complexity_ of changes (and components) manageable.

**Comment by RubenVerborgh** [comment]
Another angle at this is the ability to reuse components in different configurations.

"Solid server" is not the only runtime configuration that these components can be instantiated to. For instance, let's take the auth proxy notion discussed by @kjetilk: with this architecture, that is just a different configuration of components. So it would be an HTTP layer that uses `ResourceIdentifier` and `CredentialsExtractor`, but none of the others. The concept of a "WAC LDP task" would not exist, since it would not be an LDP server.

Ensuring that components don't need to know more than they strictly should, gives them independence and enables their usage in different scenarios.

**Comment by RubenVerborgh** [comment]
Happened in 0d33cdab8dd0d681ac031e1371ecd7bb8796ed80.
