### ISSUE TITLE
HttpHandler#handle should return a Promise

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#33]
+ handle(HttpRequest, HttpResponse) : void

should probably be:

+ handle(HttpRequest, HttpResponse) : Promise<void>

So the server can know when a request has been handled successfully, and/or catch errors when not.

**Comment by RubenVerborgh** [comment]
Output would be sent through `HttpResponse`, which probably be a `Writable` (like https://nodejs.org/api/http.html#http_class_http_serverresponse).

`Writable` has an `end` method for signalling completion, and can emit an `error` event when things go wrong.

We could indeed change the contract such that the return value is a `Promise<void>`, but then we probably want to have some decisions regarding:
- Who is responsible for calling `end`?
- Who is responsible for `emit`ing errors?
- What happens when the stream is ended but the promise is rejected (or vice versa)?

One way could be to avoid that `handle` itself calls `end` or `emit`, but there might be certain cases where we want `handle` to do that itself for performance reasons.

No strong feeling either way, and as far as I'm concerned, this can be an implementation detail.

**Comment by michielbdejong** [comment]
i just marked the handle function as async and await it, so that if something goes pear-shaped (e.g. sending the http error response fails), NodeJS logs the error.
