### ISSUE TITLE
Feedback on LDP layer

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/solid-server-architecture#41]
This issue summarizes some thoughts I had on the LDP layer:

* The components in `LdpHandler`, such as `TargetExtractor`, `BodyParser`, ...
  Should these become interfaces, so that (in a bus-like system) people can provide different implementations for them?
* It's not clear to me what the `TargetExtractor` will do exactly, can a description for this be added?

**Comment by RubenVerborgh** [comment]
> * The components in `LdpHandler`, such as `TargetExtractor`, `BodyParser`, ...
>   Should these become interfaces, so that (in a bus-like system) people can provide different implementations for them?

Yeah, absolutely. I just didn't want to go in that much detail in the diagram at that place. Page 2 details that `ResourceIdentifier` is also an interface, for instance.

And actually, all parsers/extractors should be aggregated components by a single `RequestParser` interface, such that `LdpHandler` only has one dependency instead of the whole bunch. The orchestration of the subparts belongs in `RequestParser`.

> * It's not clear to me what the `TargetExtractor` will do exactly, can a description for this be added?

It's the thing that creates the `ResourceIdentifier`. I.e., if I send a request to `http://1.2.3.4/foo/bar?auth=r67890` with a certain `Host` header, it will produce the identifier. It might seem trivial, but there are actually some security edge cases you want to unit test independently (https://github.com/RubenVerborgh/solid-server-ts/blob/master/src/http/TargetExtractor.ts), and then there's also Verifiable Credentials and HTTP-independence (#39).

**Comment by RubenVerborgh** [comment]
Resolving this for now, as I think it's just a matter of level of detail.
