### ISSUE TITLE
Is Operation.requiredPermissions an odd-one-out?

### ISSUE THREAD

**Issue by michielbdejong** [RubenVerborgh/solid-server-architecture#5]
So I understand an Operation object represents the processing of one specific http request (for each http request that hits the server, one Operation object is created by the OperationFactory, and it's executed making use of the Authorizer and the ResourceStore.

So I understand why the OperationFactory uses the method, target and representation from the http request to determine what type of operation to create. There, the handler code is selected based mainly on the method, and then the execute method will execute that handler code. But the required permissions depend on the handler and what it's planning to do, right? Maybe requiredPermissions should even be next to canHandle, as a thing exposed by a handler?

And who reads that requiredPermissions field, to actually compare it to Authorizer.hasPermissions and make a code-flow decision to abort with access-denied or not?

**Comment by RubenVerborgh** [comment]
> But the required permissions depend on the handler and what it's planning to do, right?

The required permission depend on the `Operation`. A quick note for clarity maybe: although `requiredPermissions` is modeled as a field in the UML diagram, the responsibility for setting the value of this field is with the individual `Operation`, not with the `OperationFactory`.

An implementation of this idea can be seen here:
- To do a `PUT` operation, the agent unconditionally needs `Write` permissions: https://github.com/RubenVerborgh/solid-server-ts/blob/master/src/ldp/operations/PutOperation.ts#L20
- To do a `PATCH` operation, the required permissions depend on the pattch in the HTTP request's body: https://github.com/RubenVerborgh/solid-server-ts/blob/master/src/ldp/operations/PatchOperation.ts#L20-L22

> Maybe requiredPermissions should even be next to canHandle, as a thing exposed by a handler?

Then we'd give them more knowledge than they need, namely, each operation would need to know where to look for the actual permissions, interface with `Authorizer`, etc. Since this functionality is common, `LdpHandler` itself can actually do this processing. `LdpHandler` just asks the `Operation` what permissions are needed, and then asks the `Authorizer` whether the agent has those permissions on the given target. That way, `LdpHandler` does _not_ know what permissions operations need; only the individual operation needs to. Similarly, `Operation` does not need to know how to check whether the agent has permissions (it even does not have a notion that there _is_ an agent), or what error should be thrown when permissions are lacking. Example of such a flow: https://github.com/RubenVerborgh/solid-server-ts/blob/a93717ec02389ba10c79975fc2bbdbe8d18336f0/src/http/ResourceStoreRequestHandler.ts#L73-L82

The idea behind this is https://github.com/solid/solid-architecture/blob/4be883518315e7bf64dd87d01802616b1b8e9859/server/request-flow.md#step-2-parse-the-request-to-the-personal-data-store

**Comment by michielbdejong** [comment]
How does LdpHandler know that it does not need to check permissions for an OPTIONS request?

**Comment by michielbdejong** [comment]
And how does the glob-read Operation trigger access checks for individual resources, after it has retrieved the folder listing?

And what if you have append access to a folder, but you use that to create a document for which you don't have write access? (normally this situation would only occur in a hash-collision, but I think through the `slug` header you can request which file name should be created; for the sake of argument we can imagine that obeying the `slug` header becomes obligatory and then the server should definitely check the resource-specific ACL, i think)

**Comment by pmcb55** [comment]
> How does LdpHandler know that it does not need to check permissions for an OPTIONS request?

It doesn't. The OPTIONS operation knows it needs 'PermissionSet.READ_ONLY' permission, since that's what the default implementation of 'get requiredPermissions()' in the abstract 'LdpOperation' base class returns.

**Comment by pmcb55** [comment]
> glob-read

Globbing will be deprecated! (But for for now, the server just iterates on the contained resources performing the incoming 'operation' for each - I don't see any issue there)

**Comment by pmcb55** [comment]
>  ...imagine that obeying the slug header becomes obligatory...

I don't understand that. The Slug header is always just a hint, always.

**Comment by RubenVerborgh** [comment]
> > How does LdpHandler know that it does not need to check permissions for an OPTIONS request?
> 
> It doesn't. The OPTIONS operation knows it needs 'PermissionSet.READ_ONLY' permission

+1

> And how does the glob-read Operation trigger access checks for individual resources, after it has retrieved the folder listing?

That's a good point. Multiple possible answers:
1. This could be where the current abstraction breaks, and the operation would need to return a map of resources and required permissions instead.
2. `target` could be a glob, and the permissions checker knows about it.
3. Globbing is not part of LDP, so it could be a different handler altogether (that makes use of some of the same building blocks).

My preference goes to answer 3.

> And what if you have append access to a folder, but you use that to create a document for which you don't have write access?

The `addResource` contract should be such that it always creates a new file, and under no circumstance overwrites anything.
